/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dutycalls;


public class ChooseCharacter extends javax.swing.JFrame {

    /**
     * Creates new form PlayerVsPlayer
     */
    public ChooseCharacter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseChar = new javax.swing.JLabel();
        btnDoctor = new javax.swing.JButton();
        btnChef = new javax.swing.JButton();
        btnPolice = new javax.swing.JButton();
        btnEngineer = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        btnFireFighter = new javax.swing.JButton();
        charTeacher = new javax.swing.JButton();
        btnJournalist = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChooseChar.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        lblChooseChar.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseChar.setText("Choose your character");
        getContentPane().add(lblChooseChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 42, -1, -1));

        btnDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charDoctor.jpg"))); // NOI18N
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 118, -1, -1));

        btnChef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charChef.jpg"))); // NOI18N
        getContentPane().add(btnChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 118, -1, -1));

        btnPolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charPolice.jpg"))); // NOI18N
        getContentPane().add(btnPolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 118, -1, -1));

        btnEngineer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charEngineer.jpg"))); // NOI18N
        getContentPane().add(btnEngineer, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 118, -1, -1));

        btnDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charDelivery.jpg"))); // NOI18N
        getContentPane().add(btnDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 279, -1, -1));

        btnFireFighter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charFireFighter.jpg"))); // NOI18N
        getContentPane().add(btnFireFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 279, -1, -1));

        charTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charTeacher.jpg"))); // NOI18N
        getContentPane().add(charTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 279, -1, -1));

        btnJournalist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/charJournalist.jpg"))); // NOI18N
        getContentPane().add(btnJournalist, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 279, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 102, 153));
        btnBack.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 404, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dutycalls/Images/bgCharacters.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 810, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChef;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnEngineer;
    private javax.swing.JButton btnFireFighter;
    private javax.swing.JButton btnJournalist;
    private javax.swing.JButton btnPolice;
    private javax.swing.JButton charTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChooseChar;
    // End of variables declaration//GEN-END:variables
}
